"""topic id added in chat table

Revision ID: 33f75a9b4e65
Revises: bdc69d183370
Create Date: 2026-07-25 07:09:43.895081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33f75a9b4e65'
down_revision: Union[str, Sequence[str], None] = 'bdc69d183370'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_chats', sa.Column('topic_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'interview_chats', 'interview_topics', ['topic_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interview_chats', type_='foreignkey')
    op.drop_column('interview_chats', 'topic_id')
    # ### end Alembic commands ###
