"""estamated_questions column added

Revision ID: cb61e1d454e6
Revises: 19c6cb1d31a0
Create Date: 2026-07-25 06:35:46.998319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb61e1d454e6'
down_revision: Union[str, Sequence[str], None] = '19c6cb1d31a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('estimated_questions', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'estimated_questions')
    # ### end Alembic commands ###
