from sqlalchemy import select, func, update
from app.models.interview_chat import InterviewChat
from app.models.interview_topics import InterviewTopics
from app.models.interview import Interview
from app.prompts.prompts import question_generating_prompt, first_question_prompt, next_question_prompt
from app.schema.PydanticSchema import LLMQuestionType, InterviewEvaluationResponse
from app.agents.ask_llm import ask_llm
from app.models.interview_chat import ResponedBy
from app.models.llm_usage import LLMUsage
from app.models.interview_evaluations import InterviewEvaluation
from app.core.config import LLM_MODEL
import traceback
from sqlalchemy.orm import Session
from app.core.ws import send_socket_status



class QuestionGenerator():
    def __init__(self, db, interview_id):
        self.db : Session  = db
        self.interview_id = interview_id
        self._load_interview_info()
        self._load_interview_topics()
        
    def generate_first_question(self):
        ### 1. Fetch interview details
        ### 2. Fetch interview first topic
        ### 3. Get the prompt
        ### 4. Generate the question and save it in table
        ### 5. Save the question and usage
        ### 5. 
        ### 6. 
        
        try:
            ### 1. Fetch interview details
            interview_info = self.interview_info
            
            ### 2. Fetch interview first topic
            first_interview_topic = self.interview_topics[0] # self.db.query(InterviewTopics).where(InterviewTopics.interview_id == interview_id).order_by(InterviewTopics.order.asc()).one_or_none()
            ### 3. Get the prompt
            first_prompt = first_question_prompt(
                role=interview_info.role,
                technology=interview_info.technology,
                experience=interview_info.experience,
                difficulty=interview_info.difficulty,
                question_type=interview_info.question_type,
                topic=first_interview_topic.topic)
            ### 4. Generate the question 
            response = ask_llm(prompt=first_prompt)
            ### 5. Save the question
            question_res = response.text
            usage = response.usage
            
            question_generated = InterviewChat(
                interview_id=self.interview_id,
                topic_id=first_interview_topic.id,
                response=question_res["question"],
                responded_by=ResponedBy.AI,
                response_status="generated"
            )
            
            self.db.add(question_generated)
            self.db.flush()
            self.db.refresh(question_generated)
            
            ### 6. Save the usage
            self.db.add(
                LLMUsage(
                    model=LLM_MODEL,
                    reference_name="interview_chat.id",
                    reference_id=question_generated.id,
                    prompt_tokens=usage["prompt_tokens"],
                    completion_tokens=usage["completion_tokens"],
                    total_tokens=usage["total_tokens"]
                )
            )
            return {
                "completed": False,
                "message" : question_generated,
                "status" : "success"                
            }
            
        except:
            raise Exception(
                "Failed to generate first question"
            )
    
    ## 1. Fetch last topic
    ## 2. Fetch Last Topic Question & Answer only, if the last topic has only one question & answer
    ## 3. Fetch next topic for question generation
    ## 4. If there are no topics return interview completed
    ## 5. Fetch the interview history so LLM won't repeat questions
    ## 6. Generate the prompt from the above data
    ## 7. Generate response from LLM using the above question generating prompt
    ## 8. Store the question generated by LLM in the interview_chat table
    ## 9. Store the LLM usage in table
    def generate_question(self, interview_id):
        try:
            
            # =========================== Question Generating Process ===========================
            interview = self.db.query(Interview).where(Interview.id == interview_id).one_or_none()
            # ========================================================================================
            ## 1. Fetch last topic
            print("##### 1 #####")
            # ========================================================================================
            last_topic_stmt = (
                select(
                    func.count(InterviewChat.topic_id).label("no_of_topics"),
                    InterviewTopics.topic,
                    InterviewChat.topic_id
                )
                .join(
                    InterviewTopics,
                    InterviewChat.topic_id == InterviewTopics.id,
                )
                .where(InterviewChat.interview_id == interview_id)
                .group_by(InterviewChat.topic_id, InterviewTopics.id, InterviewTopics.topic)
                .order_by(InterviewTopics.order.desc())
                .limit(1)
            )
            last_topic = self.db.execute(last_topic_stmt).one_or_none()
            # ========================================================================================
            ## 2. Fetch Last Topic Question & Answer only, if the last topic has only one question & answer
            print("##### 2 #####")
            # ========================================================================================
            previous_question = ""
            follow_up_asked = False
            previous_topic_name = ""
            if last_topic and last_topic.no_of_topics < 2:
                q_and_a = self.db.query(InterviewChat).where(
                    InterviewChat.interview_id == interview_id,
                    InterviewChat.topic_id == last_topic.topic_id
                ).all()
                for qa in q_and_a:
                    previous_question += f"Question: {qa.response}\n" if qa.responded_by == 'ai' else f"Answer: {qa.response}\n"
                    follow_up_asked = True
                previous_topic_name = last_topic.topic
                
            # ========================================================================================
            ## 3. Fetch next topic for question generation
            print("##### 3 #####")
            # ========================================================================================
            covered_topic_ids = select(InterviewChat.topic_id).where(InterviewChat.interview_id == interview_id)
            next_topic_stmt = (
                    select(InterviewTopics.topic, InterviewTopics.id)
                    .where(
                        InterviewTopics.interview_id == interview_id,
                        InterviewTopics.id.not_in(covered_topic_ids)
                    )
                    .order_by(InterviewTopics.order.asc())
                    .limit(1)
            )
            next_topic = self.db.execute(next_topic_stmt).one_or_none()
            
            # ========================================================================================
            ## 4. If there are no topics return interview completed
            print("##### 4 #####")
            # ========================================================================================
            if next_topic is None:
                update_stmt = (
                    update(Interview)
                    .where(Interview.id == interview_id)
                    .values(status="completed")
                )
                self.db.execute(update_stmt)
                self.db.commit()
                return {
                    "completed": True,
                    "success": True,
                    "message": "Interview Completed",
                    "interview_info": interview,
                    "error": ""
                }
            # ========================================================================================
            ## 5. Fetch the interview history so LLM won't repeat questions
            print("##### 5 #####")
            # ========================================================================================
            context = ""
            topicId = last_topic.topic_id if not last_topic is None else 0
            all_questions_answers = self.db.query(InterviewChat).where(InterviewChat.interview_id == interview_id, InterviewChat.topic_id != topicId).order_by(InterviewChat.created_at.asc()).all()


            for item in all_questions_answers:
                context += f"Question: {item.response}\n" if item.responded_by == 'ai' else f"Answer: {item.response}\n"
            
            
            # ========================================================================================
            ## 6. Generate the prompt from the above data
            print("##### 6 #####")
            # ========================================================================================
            question_prompt = question_generating_prompt(
                role=interview.role,
                technology=interview.technology,
                experience=interview.experience,
                difficulty=interview.difficulty,
                question_type=interview.question_type,
                topic=next_topic.topic,
                context=context,
                follow_up_asked=follow_up_asked,
                previous_topic=previous_topic_name,
                previous_topic_q_and_a=previous_question,
            )
            
            # ========================================================================================
            ## 7. Generate response from LLM using the above question generating prompt
            print("##### 7 #####")
            # ========================================================================================
            question_response = ask_llm(question_prompt)
            
            
            question_gen_text: LLMQuestionType = question_response["text"]
            
            
            # ========================================================================================
            ## 8. Store the question generated by LLM in the interview_chat table
            print("##### 8 #####")
            # ========================================================================================
            question_generated = InterviewChat(
                interview_id=interview.id,
                topic_id=next_topic.id,
                response=question_gen_text["question"],
                responded_by=ResponedBy.AI,
                response_status="generated"
            )

            self.db.add(question_generated)
            self.db.flush()
            self.db.refresh(question_generated)
            
            # ========================================================================================
            ## 9. Store the LLM usage in table
            print("##### 9 #####")
            # ========================================================================================
            self.db.add(
                LLMUsage(
                    model=LLM_MODEL,
                    reference_name="interview_chat.id",
                    reference_id=question_generated.id,
                    prompt_tokens=question_response["usage"]["prompt_tokens"],
                    completion_tokens=question_response["usage"]["completion_tokens"],
                    total_tokens=question_response["usage"]["total_tokens"]
                )
            )
            return {
                "completed": False,
                "message" : question_generated,
                "status" : "success"                
            }
        except Exception as e:
            tb = traceback.extract_tb(e.__traceback__)
            print(" =================================================== ")
            print("Error: ", str(e))
            print(f"Error Info: {tb[-1].filename} - {tb[-1].lineno}")
            print(" =================================================== ")
            raise Exception(
                "Failed to generate question"
            )
            
    # 
    async def analyze_and_next_question(self):
        await send_socket_status(self.interview_id, "Started generating next question.")        
        
        ### 1. Get the last topic details & Next topic details
        
        from sqlalchemy import func, case, literal
        # A RECORD IS INSERTED IN INTERVIEW_CHAT TABLE BEFORE COMMING TO THIS FUNCTION. THAT MEANS NOW INTERVIEWW_CHAT TABLE HAS QUESTION AND IT'S ANSWER

        
        
        current_topic_info = self.db.query(InterviewTopics).where(InterviewTopics.interview_id == self.interview_id, InterviewTopics.id.in_(
            self.db.query(InterviewChat.topic_id).where(InterviewChat.interview_id == self.interview_id)
        )).order_by(InterviewTopics.order.desc()).limit(1).one_or_none()
        
        next_topic_info = self.db.query(InterviewTopics).where(InterviewTopics.interview_id == self.interview_id, InterviewTopics.id.not_in(
            self.db.query(InterviewChat.topic_id).where(InterviewChat.interview_id == self.interview_id)
        )).order_by(InterviewTopics.order.asc()).limit(1).one_or_none()

        current_topic_chat = self.db.query(InterviewChat).where(InterviewChat.topic_id == current_topic_info.id).order_by(InterviewChat.id.desc()).all()
        current_topic = current_topic_info.topic
        current_question = ""
        current_answer = ""
        
        ### 2. Check how many questions were asked on that topic
        if len(current_topic_chat) < 4:
            for item in current_topic_chat:
                if item.responded_by == "ai":
                    current_question = item.response
                else :
                    current_answer = item.response
        
        print("Question on current topic : ", len(current_topic_chat))

        previous_questions_query = self.db.query(InterviewChat).where(InterviewChat.interview_id == self.interview_id, InterviewChat.id != current_topic_chat[-1].id, InterviewChat.responded_by == ResponedBy.AI).all()

        all_previous_questions = "\n".join(item.response for item in previous_questions_query if item.responded_by == ResponedBy.AI)
                
        ### 1.1 fetch last topic id
        ### 1.2 concat statement
        ### 1.3 number of question were asked on last topic
        prompt = next_question_prompt(
            role=self.interview_info.role,
            technology=self.interview_info.technology,
            experience=self.interview_info.experience,
            difficulty=self.interview_info.difficulty,
            question_type=self.interview_info.question_type,
            current_topic=current_topic,
            current_question=current_question,
            candidate_answer=current_answer,
            next_topic=next_topic_info.topic,
            previous_questions=all_previous_questions,
        )
        ### 3. If asked questions are 4 then go to the next topic
        
        ### 4. If only one question is asked then let LLM decide weather followup question required or not based on last question & answer.
        llm_response = ask_llm(prompt)
        llm_response_text:InterviewEvaluationResponse = llm_response["text"]
        print("########### LLM TEXT ###########")
        print(llm_response_text)
        print("########### LLM TEXT ###########")
        
        await send_socket_status(self.interview_id, "LLM responded successfully.")
        ### 5. From the LLM response save the generated question into the database with following topic
        # llm_response.usage
        
        new_question_insert = InterviewChat(
            interview_id=self.interview_id,
            topic_id=current_topic_info.id if llm_response_text["next_action"] == "follow_up" else next_topic_info.id,
            response=llm_response_text["question"],
            responded_by=ResponedBy.AI,
            response_status="generated"
        )

        self.db.add(new_question_insert)

        self.db.flush()
        ### 6. Store the LLM usage
        llm_usage_insert = LLMUsage(
            reference_id=new_question_insert.id,
            reference_name="interview_chat.id",
            completion_tokens = llm_response["usage"]["completion_tokens"],
            prompt_tokens = llm_response["usage"]["prompt_tokens"],
            total_tokens = llm_response["usage"]["total_tokens"],
            model=LLM_MODEL       
        )
        self.db.add(llm_usage_insert)
        self.db.flush()
        
        await send_socket_status(self.interview_id, "Token usage saved.")
        
        
        
        interview_evaluation_insert = InterviewEvaluation(
            chat_id=current_topic_chat[-1].id,
            score=llm_response_text["score"],
            technical_accuracy=llm_response_text["technical_accuracy"],
            completeness=llm_response_text["completeness"],
            relevance=llm_response_text["relevance"],
            answer_quality=llm_response_text["answer_quality"],
            strengths=llm_response_text["strengths"],
            weaknesses=llm_response_text["weaknesses"],
            missing_concepts=llm_response_text["missing_concepts"],
            improved_answer=llm_response_text["improved_answer"],
            follow_up_required=llm_response_text["follow_up_required"],
            follow_up_reason=llm_response_text["follow_up_reason"],
            next_action=llm_response_text["next_action"],
        )
        self.db.add(interview_evaluation_insert)

        self.db.flush()
        
        await send_socket_status(self.interview_id, "Question generated successfully.")
        
        
        
        await send_socket_status(self.interview_id, "New question generated successfully.")

        return {
            "completed": False,
            "message" : new_question_insert,
            "status" : "success"                
        }
        
        # send_socket_status(self.interview_id, "Question generated successfully.")
        # return 
    
    def _load_interview_info(self):
        self.interview_info = self.db.query(Interview).where(Interview.id == self.interview_id).one_or_none()
        
    def _load_interview_topics(self):
        self.interview_topics = self.db.query(InterviewTopics).where(InterviewTopics.interview_id == self.interview_id).order_by(InterviewTopics.order.asc()).all()

    def _get_last_question_answer(self):
        self.chat = self.db.query(InterviewChat).where(InterviewChat.interview_id == self.interview_id).order_by(InterviewChat.created_at.desc()).all()